scanner/src/main/java/no/nordicsemi/android/kotlin/ble/scanner/data/Mappers.kt
Fix NullPointerException which occurs during parsing scan result.
The issue has been observed on Firebase console, but because of limited 
information the true cause is unknown. To prevent the issue elvis operator
has been added to different elements of scan result's parsing.
Fatal Exception: java.lang.NullPointerException
no.nordicsemi.android.kotlin.ble.scanner.BleScanner$scan$1$scanCallback$1.onScanResult (BleScanner.kt:100)
android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run (BluetoothLeScanner.java:669)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
=> Fix NullPointer exception during scanning

uiscanner/build.gradle.kts
As the `:uiscanner` module takes care of scanning, exposing `:scanner` is not necessary, I believe, but to get scan results the target app needs to have access to core classes.
=> Exposing `:blek:core` from `uiscanner` module

client/build.gradle.kts, client/src/main/java/no/nordicsemi/android/kotlin/ble/client/main/bonding/BondingBroadcastReceiver.kt, core/src/main/java/no/nordicsemi/android/kotlin/ble/core/data/BleGattConnectionPriority.kt
- Register BondingBroadcastReceiver with RECEIVER_NOT_EXPORTED flag.
- Improve BleGattConnectionPriority docs.
=> Feat: receiver not exported

server/src/main/java/no/nordicsemi/android/kotlin/ble/server/main/ServerBleGatt.kt, server/src/main/java/no/nordicsemi/android/kotlin/ble/server/main/ServerConnectionEvent.kt
Add a way to observe server disconnections
Before it was possible to observe disconnections by saving the map emitted by "connections" flow and comparing it to the last one received to see if any value was deleted, but this implementation should make this easier
Tested by building the library and using it in my app. Usage is :
```kotlin
serverBleGatt.connectionEvents
.onEach {
when(it) {
is ServerConnectionEvent.DeviceConnected -> {
configureServices(it.connection.services)
}
is ServerConnectionEvent.DeviceDisconnected -> {
Timber.e("Server disconnected")
}
}
}
.collect()
```
=> Add a way to observe server disconnections

client-android/src/main/java/no/nordicsemi/android/kotlin/ble/client/real/NativeClientBleAPI.kt, client-api/src/main/java/no/nordicsemi/android/kotlin/ble/client/api/GattClientAPI.kt, client-mock/src/main/java/no/nordicsemi/android/kotlin/ble/client/mock/BleMockGatt.kt, client/src/main/java/no/nordicsemi/android/kotlin/ble/client/main/callback/ClientBleGatt.kt, client/src/main/java/no/nordicsemi/android/kotlin/ble/client/main/callback/ClientBleGattFactory.kt, core/src/main/java/no/nordicsemi/android/kotlin/ble/core/data/BleGattConnectOptions.kt, mock/src/main/java/no/nordicsemi/android/kotlin/ble/mock/MockEngine.kt, server-mock/src/main/java/no/nordicsemi/android/kotlin/ble/server/mock/MockServerAPI.kt
Add possibility to reuse `ClientBleGatt` after device disconnects.
- Add `closeOnDisconnect ` parameter to `BleGattConnectOptions` indicating whether `gatt.close()` should be called after disconnection.
- Add `reconnect()` function to  `ClientBleGatt`.
=> Add close on disconnect parameter to ClientBleGatt

core/src/main/java/no/nordicsemi/android/kotlin/ble/core/scanner/BleGattPrimaryPhy.kt, scanner/src/main/java/no/nordicsemi/android/kotlin/ble/scanner/data/Mappers.kt
Fatal Exception: java.lang.IllegalArgumentException
Cannot create BleGattPrimaryPhy for value: 0
no.nordicsemi.android.kotlin.ble.core.scanner.BleGattPrimaryPhy$Companion.create (BleGattPrimaryPhy.java:294)
no.nordicsemi.android.kotlin.ble.scanner.data.MappersKt.toDomain (Mappers.kt:294)
no.nordicsemi.android.kotlin.ble.scanner.MapperKt.toScanItem (Mapper.kt:294)
=> Fix IllegalArgumentException

server/src/main/java/no/nordicsemi/android/kotlin/ble/server/main/ServerBleGatt.kt, server/src/main/java/no/nordicsemi/android/kotlin/ble/server/main/service/ServerBluetoothGattConnection.kt
A nicer version for resource handling. If you need to clean up resources per connection, use:
```
connection.connectionScope.launch {
try {
awaitCancellation()
} catch (_: CancellationException) {
cleanup()
}
}
```
Any subscriptions to flows to be pushed via setValue() can also be attached to `connectionScope`.
```
connection.connectionScope.launch {
otherFlow.collect {
characteristic.setValue(it)
}
}
```
=> connectionScope for #44

core/src/main/java/no/nordicsemi/android/kotlin/ble/core/scanner/BleScanResults.kt, scanner/src/main/java/no/nordicsemi/android/kotlin/ble/scanner/BleScanner.kt, uiscanner/src/main/java/no/nordicsemi/android/kotlin/ble/ui/scanner/ScannerScreen.kt, uiscanner/src/main/java/no/nordicsemi/android/kotlin/ble/ui/scanner/ScannerView.kt, uiscanner/src/main/java/no/nordicsemi/android/kotlin/ble/ui/scanner/main/viewmodel/ScannerViewModel.kt
This PR adds the following improvements:
1. Advertised name is used on the Scanner views instead of device name (cached value from `BluetoothDevice.name`)
2. New `advertisedName` computed property added to `BleScanResults`
This PR fixes the following bug:
*In nRF DFU after a succesful DFU the device name gets cleared (`refresh()` called). When trying to scan the device for the second time, the scan ends with nothing, as the device gets filtered out due to "lack of name". However, the name from the advertising packet is not null and is ignored.*
=> Displaying advertised name instead of the cached one

uiscanner/src/main/java/no/nordicsemi/android/kotlin/ble/ui/scanner/ScannerScreen.kt, uiscanner/src/main/java/no/nordicsemi/android/kotlin/ble/ui/scanner/ScannerView.kt, uiscanner/src/main/java/no/nordicsemi/android/kotlin/ble/ui/scanner/main/viewmodel/ScannerViewModel.kt
My last PR #71 forced using the name from the advertising data. However, bonded devices which do not advertise don't have such, therefore were filtered out when Name filter was selected. This PR fixes that by checking both names. The UI displays the advertised name with higher priority.
=> Fixed displaying bonded devices which have no advertising data

core/src/main/java/no/nordicsemi/android/kotlin/ble/core/scanner/BleScannerSettings.kt, scanner/src/main/java/no/nordicsemi/android/kotlin/ble/scanner/BleScanner.kt
Fix #64: Bonded devices are returned from scans even if they don't match filter
=> Fix #64: Bonded devices are not filtered

server/src/main/java/no/nordicsemi/android/kotlin/ble/server/main/service/ServerBleGattCharacteristic.kt
Fix #62: Change confusing function names for setting value on a server
=> Fix #62: Change confusing function names for setting value on a server

uiscanner/src/main/java/no/nordicsemi/android/kotlin/ble/ui/scanner/main/DeviceListItem.kt
On ScannerView devices with no name were shown without any name. The default name, I guess, is "", not null.
Both "" and null are shown as "_No name_".
=> Fixed printing "No name" when the device name is empty

build.gradle.kts, gradle/libs.versions.toml, uiscanner/build.gradle.kts, uiscanner/src/main/java/no/nordicsemi/android/kotlin/ble/ui/scanner/ScannerView.kt, uiscanner/src/main/java/no/nordicsemi/android/kotlin/ble/ui/scanner/view/ScannerAppBar.kt, uiscanner/src/main/java/no/nordicsemi/android/kotlin/ble/ui/scanner/view/internal/FilterView.kt, uiscanner/src/main/java/no/nordicsemi/android/kotlin/ble/ui/scanner/view/internal/ScanEmptyView.kt, uiscanner/src/main/java/no/nordicsemi/android/kotlin/ble/ui/scanner/view/internal/ScanErrorView.kt
Material 3 version 1.2.0-alpha11 adds PullToRefresh component.
This PR also removes unused dependencies from internal toml file.
=> UI Scanner migrated to Material 3 version 1.2.0-alpha11

client/src/main/java/no/nordicsemi/android/kotlin/ble/client/main/service/ClientBleGattCharacteristic.kt
Enabling notifications on the `onStart` block will cause loss of notifications since `onStart` is called too late. Moved the enabling to an also block instead.
=> Fix Missing Notifications

app_client/src/main/java/no/nordicsemi/android/kotlin/ble/app/client/Destinations.kt, uiscanner/src/main/java/no/nordicsemi/android/kotlin/ble/ui/scanner/ScannerScreen.kt, uiscanner/src/main/java/no/nordicsemi/android/kotlin/ble/ui/scanner/ScannerView.kt, uiscanner/src/main/java/no/nordicsemi/android/kotlin/ble/ui/scanner/main/viewmodel/ScannerViewModel.kt, uiscanner/src/main/java/no/nordicsemi/android/kotlin/ble/ui/scanner/view/internal/FilterView.kt
This PR modifies #148 by allowing filtering in both states: selected and unselected.
This allows to create "All" filter like before, which was filtering when unselected, or "Unprovisioned", which filters for supported devices in any of the states in addition to filtering provisioning state.
=> Allowing filtering with filter selected and unselected

gradle/libs.versions.toml
The 2.3 update migrated release scripts to use Dokka instead of Javadoc.
Javadoc was failing to compile using Java 17: https://github.com/Kotlin/dokka/issues/2956
=> Nordic plugins set to 2.3

scanner/src/main/java/no/nordicsemi/android/kotlin/ble/scanner/BleScanner.kt
From now one scanner won't return bonded devices that don't support Bluetooth LE.
=> Skip bonded Bluetooth Classic devices

client-core-android/src/main/java/no/nordicsemi/kotlin/ble/client/android/ScanFilterScope.kt, client-core-android/src/main/java/no/nordicsemi/kotlin/ble/client/android/internal/ScanFilters.kt, sample/src/main/java/no/nordicsemi/kotlin/ble/android/sample/scanner/ScannerViewModel.kt
This PR fixes #172.
I checked, that the native Android API allows for `null` in `manufacturerData` as long as `companyId > 0` (for some reason).
It also only checks the bytes up-to to the given filter length, so if filter data are empty - it only checks for Company ID.
I tested the new feaure and it seems to be working fine.
=> Allow scanning for Manufacturer Data by Company ID only

client-android/src/main/java/no/nordicsemi/kotlin/ble/client/android/internal/ScanFilterUtils.kt, client-core-android/src/main/java/no/nordicsemi/kotlin/ble/client/android/internal/ScanFilters.kt, sample/src/main/java/no/nordicsemi/kotlin/ble/android/sample/scanner/ScannerViewModel.kt
This PR fixes a bug, where no scan results are returned if one scans with the following filters:
```kotlin
Any {
Name("Some Name")
Name(Regex("Prefix.*")
}
```
if there is a device advertising with some Prefix.
The regular names were converted to `ScanFilter` and applied to the scanner, so no other result was passed. As the regex condition is checked only in the library, after results are delivered, no devices were reported.
The change adds an empty filter in this case with no name to be passed for the sake of checking it against all filters in the library.
=> Bugfix: Correctly scan for name as Regex

client-core/src/main/java/no/nordicsemi/kotlin/ble/client/ScanResult.kt
From now on `distinctByPeripheral` won't alter the returned type.
=> Fixed return type of `distinctByPeripheral`

client-android/src/main/java/no/nordicsemi/kotlin/ble/client/android/internal/NativeExecutor.kt, client-core/src/main/java/no/nordicsemi/kotlin/ble/client/internal/CentralManagerImpl.kt, core/src/main/java/no/nordicsemi/kotlin/ble/core/ConnectionState.kt
This PR improves handing disconnection:
1. When `peripheral.close()` was called twice in a row, the `gatt.disconnect()` and `gatt.close()` methods were called twice.
2. Closing Central Manager's scope will also close the Central Manager and its periipherals.
3. A helper method added to `ConnectionState.Disconnected.Reason` to check whether the disconnection was user initiated.
=> Disconnection improvements

client-core/src/main/java/no/nordicsemi/kotlin/ble/client/Peripheral.kt, sample/src/main/java/no/nordicsemi/kotlin/ble/android/sample/scanner/ScannerViewModel.kt
`peripheral.services()` returns a `StateFlow`, hence must have an initial state.
`peripheral.services()` was returning an empty list.
This was problematic, as it was not possible to figure out whether a device had a specific service, or not, when service discovery was done with a filter. Initial state of this flow was `[]`, and when the required service was not found, the flow did not emit anything.
The returned type of `peripheral.services(...)` was changed to optional: `List<RemoteService>?` with `null` as an initial state. When service discovery is complete, the flow emits `[]` indicating that the service was not found.
=> Breaking: service discovery API improvement

client-core/src/main/java/no/nordicsemi/kotlin/ble/client/Peripheral.kt
Before, when the device, which was connected using `ConnectionOptions.AutoConnect` was disconnected at the moment when `peripheral.disconnect()` was called, the automatic connection was not stopped.
This change makes sure that the `gatt.close` gets called.
=> Make sure the `disconnect()` method closes AutoConnect connection

client-android-mock/src/main/java/no/nordicsemi/kotlin/ble/client/android/mock/internal/MockCentralManagerImpl.kt, client-android/src/main/java/no/nordicsemi/kotlin/ble/client/android/internal/NativeCentralManagerImpl.kt, client-core-android/src/main/java/no/nordicsemi/kotlin/ble/client/android/internal/CentralManagerImpl.kt
This is only internal implementation.
=> Unnecessary generic type removed from `CentralManagerImpl` type

client-android-mock/src/main/java/no/nordicsemi/kotlin/ble/client/android/mock/internal/MockCentralManagerImpl.kt, client-android/src/main/java/no/nordicsemi/kotlin/ble/client/android/internal/NativeCentralManagerImpl.kt
`centralManager.close()` was unregistering broadcast receivers twice and crashing when called simultaneously.
The second call was introduced in #190.
=> Bugfix: `close()` was unregistering broadcast receivers twice

client-android-mock/src/main/java/no/nordicsemi/kotlin/ble/client/android/mock/internal/MockCentralManagerImpl.kt, client-core/src/main/java/no/nordicsemi/kotlin/ble/client/CentralManager.kt
Just like `BluetoothAdapter.getRemoteDevice(..)` always returns a `BluetoothDevice`, 
the `centralManager.getPeripheralById(...)` always can return a `Peripheral`.
In mock implementation, if the is no `PeripheralSpec` for the given id, a "dummy" one will be created. The simulated peripheral won't advertise and won't be reachable, just as if someone tried to connect to an unreachable device.
On iOS, the [retrieveperipherals(withidentifiers:)](https://developer.apple.com/documentation/corebluetooth/cbcentralmanager/retrieveperipherals(withidentifiers:)) method may not return a `CBPeripheral` for some random UUID, therefore we cannot guarantee, that the list returned by `getPeripheralsById` will have the same size as the provided list of ids, hence the `getPeripheralById` may return `null`. …
=> Breaking: `getPeripheralById` no longer returns null

client-core-android/src/main/java/no/nordicsemi/kotlin/ble/client/android/CentralManager.kt, client-core-android/src/main/java/no/nordicsemi/kotlin/ble/client/android/Peripheral.kt, client-core/src/main/java/no/nordicsemi/kotlin/ble/client/Peripheral.kt, sample/src/main/java/no/nordicsemi/kotlin/ble/android/sample/scanner/ScannerViewModel.kt
A new parameter has been added to `ConnectionOptions` which will trigger automatic MTU request immediately after establishing connection.
Before it could be achieved by calling `requestHighestValueLength()` method for `Direct` connection, but for `AutoConnect` it would have to be done in `state` flow collector. With another collector observing `services()`, the service discovery was started together or after service discovery. The new option allows for automatic request for both connection types.
`AutoConnect` was changed from `data object` to `data class`. You may need to add parenthesis. See `ScanerViewModel` at the very bottom of this PR.
=> Automatic MTU request

client-android/src/main/java/no/nordicsemi/kotlin/ble/client/android/internal/Mapper.kt, core/src/main/java/no/nordicsemi/kotlin/ble/core/ConnectionState.kt
A remote device was erased and flashed with firmware that supports bonding.
On Android phone I had bond information from the previous connection, no longer valid.
When trying to connect Android is not able to re-establish security and fails with error 5 (_GATT_INSUFFICIENT_AUTHENTICATION_).
This error is now reported as `Disconnected.Reason.InsufficientAuthentication`.
=> New disconnection reason: Insufficient Authentication
